#pragma once

#include <string>
#include <CPPRegistry/Macros/Type/TypeMacros.h>

#define TYPE_REGISTRY(REGISTRY_NAME, BASE_TYPE) \
	BASIC_TYPE_REGISTRY(REGISTRY_NAME, std::string, BASE_TYPE)

#define REGISTER_NAMED_TYPE(REGISTRY, TYPE) \
	REGISTERED_TYPE(REGISTRY, TYPE, #TYPE)

#define REGISTERED_NAMED_TYPE(REGISTRY, TYPE) \
	REGISTERED_TYPE(REGISTRY, TYPE, #TYPE)