#pragma once

#include <string>
#include <CPPRegistry\MemberFunctionMacros.h>

#define MEMBER_FUNCTION_REGISTRY(REGISTRY_NAME, RETURN_TYPE, OBJECT_TYPE, ...) \
	BASIC_MEMBER_FUNCTION_REGISTRY(REGISTRY_NAME, std::string, RETURN_TYPE, OBJECT_TYPE, __VA_ARGS__)

#define REGISTER_NAMED_MEMBER_FUNCTION(REGISTRY, FUNCTION) \
	REGISTER_MEMBER_FUNCTION(REGISTRY, FUNCTION, #FUNCTION)